# Generated by Django 5.2.9 on 2026-04-14 14:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import aap_eda.core.enums


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_activation_enable_persistence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "job_type",
                    models.TextField(
                        choices=[
                            ("cleanup_audit_logs", "cleanup_audit_logs"),
                            (
                                "cleanup_stale_activations",
                                "cleanup_stale_activations",
                            ),
                        ]
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "core_management_job",
                "ordering": ("name",),
                "default_permissions": ("view", "change"),
            },
        ),
        migrations.CreateModel(
            name="ManagementJobExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default=aap_eda.core.enums.ExecutionStatus["PENDING"],
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("output", models.TextField(blank=True, default="")),
                ("errors", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered this execution (null for scheduled runs)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="management_job_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "management_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="core.managementjob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "core_management_job_execution",
                "ordering": ("-started_at",),
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="ManagementJobSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule",
                    models.TextField(
                        help_text="Cron expression (e.g., '0 2 * * *' for daily at 2 AM)"
                    ),
                ),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "management_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="core.managementjob",
                    ),
                ),
            ],
            options={
                "db_table": "core_management_job_schedule",
                "ordering": ("management_job__name",),
            },
        ),
        migrations.AddIndex(
            model_name="managementjob",
            index=models.Index(
                fields=["job_type"], name="ix_management_job_type"
            ),
        ),
        migrations.AddIndex(
            model_name="managementjobexecution",
            index=models.Index(
                fields=["started_at"], name="ix_mgmt_job_exec_started"
            ),
        ),
        migrations.AddIndex(
            model_name="managementjobexecution",
            index=models.Index(
                fields=["status"], name="ix_mgmt_job_exec_status"
            ),
        ),
    ]
